### ISSUE TITLE
Double UTF-8 encoding

### ISSUE THREAD

**Issue by ghost** [Robertof/perl-www-telegram-botapi#11] opened 2016-08-21 22:52 UTC
Hello!
I've got a small issue with 0.06 version.

All my text is in UTF-8 (cyrillic), and after calling
`Encode::encode ("utf-8",`
for whole message all text messages become unreadable at all.

**Comment by Robertof** [comment] 2016-08-21 22:57
Hey,

thanks for your report! I was afraid that the latest update could cause problems.
Are you calling `Encode::encode` manually? Do you mind posting a little example code?

Thanks!

**Comment by Robertof** [comment] 2016-08-21 23:03
Addendum: if your text is stored in code, try adding `use utf8` to the top of your source code. Thanks!

**Comment by ghost** [comment] 2016-08-21 23:36
Ciao!
I have `use utf8`, in fact all text is sent as octets I guess (as mentioned [here](https://github.com/Robertof/perl-www-telegram-botapi/issues/10)).

Here's an example (sources are in utf-8 on a utf-8 system, running Perl 5.16.3):
`$api->sendMessage ({
        parse_mode               => 'HTML',
        disable_web_page_preview => 1,
        chat_id => $u->{message}->{chat}->{id},
        text    => "Привет!"
      });`

I guess it might work as expected if `encode` is called when `is_utf8` returns false in BotAPI.pm, I'll try this tomorrow.

**Comment by Robertof** [comment] 2016-08-21 23:40
Alright, I found the issue: I should only use `Encode::encode` when there are file uploads -- otherwise everything is handled by `JSON::MaybeXS`. A fix is in the works!

**Comment by Robertof** [comment] 2016-08-22 00:18
I pushed 87800b1 right now which should fix the issue. Are you willing to test your code against this commit to see if the issue is resolved?

Thank you.

**Comment by ghost** [comment] 2016-08-22 08:22
Placed new PM file instead of 0.05.
Works fine!

**Comment by Robertof** [comment] 2016-08-22 23:09
Okay, I just released v0.07 which should put an end to encoding issues.

Thanks for your valuable contribution!

**Closed as completed by Robertof** 2016-08-22 23:09 UTC
Labels: bug
